# Generated by Django 4.1.3 on 2023-03-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_email_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'please enter a valid email address'}, max_length=254),
        ),
    ]
