# Generated by Django 4.1.3 on 2023-03-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_slug_alter_job_image_alter_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
    ]
