# Generated by Django 4.1.3 on 2023-03-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_job_type_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
